#!/bin/bash
# infra/scripts/render-ssh-config.sh
#
# Renders ssh-config from .substrate-state/remote-hosts.txt (s010 10.d).
# Each registered remote host gets a stanza pointing at its per-host
# private key under /home/agent/.ssh-remote-hosts/<name>/, the cumulative
# known-hosts at /home/agent/.ssh-known-hosts, and forces
# StrictHostKeyChecking + BatchMode + IdentitiesOnly so agent-driven SSH
# is non-interactive.
#
# Output paths:
#   .substrate-state/ssh-config             (canonical; for inspection)
#   infra/keys/architect/config             (copy; bind-mounted into the
#   infra/keys/coder/config                  role's .ssh dir as ./config)
#   infra/keys/auditor/config
#
# Why three copies rather than a single bind-mount file at
# /home/agent/.ssh/config: the role's compose service bind-mounts
# infra/keys/<role>/ at /home/agent/.ssh/ read-only, and Docker rejects
# layering a sub-file mount inside a :ro parent ("read-only file system"
# at mountpoint creation). Putting the config file inside the role's
# already-mounted keys dir sidesteps the layering and preserves :ro on
# the parent. The role containers see the ssh-config naturally at
# /home/agent/.ssh/config.
#
# All three copies share content; they're regenerated on every setup
# run and on every --add-remote-host. Since infra/keys/<role>/*  is
# already gitignored, the per-role config files are never committed.
#
# Usage:
#   render-ssh-config.sh
#       Reads .substrate-state/remote-hosts.txt and writes the four
#       output files. Always writes them even when no hosts are
#       registered (header-only file is fine — OpenSSH accepts it).

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
state_dir="${repo_root}/.substrate-state"
state_file="${state_dir}/remote-hosts.txt"
canonical="${state_dir}/ssh-config"

mkdir -p "${state_dir}"

{
    cat <<'HEADER'
# GENERATED by infra/scripts/render-ssh-config.sh — DO NOT EDIT.
# Source: .substrate-state/remote-hosts.txt
# Re-render via setup or by running this script directly.
HEADER

    if [ -f "${state_file}" ]; then
        # State file is TSV: <name>\t<user>\t<host>\t<port>.
        while IFS=$'\t' read -r name user host port; do
            [ -z "${name}" ] && continue
            cat <<STANZA

Host ${name}
    HostName ${host}
    User ${user}
    Port ${port}
    IdentityFile /home/agent/.ssh-remote-hosts/${name}/id_ed25519
    IdentitiesOnly yes
    UserKnownHostsFile /home/agent/.ssh-known-hosts
    StrictHostKeyChecking yes
    BatchMode yes
    ConnectTimeout 10
STANZA
        done < "${state_file}"
    fi
} > "${canonical}"
chmod 0644 "${canonical}"

# Mirror into each role's keys dir.
for role in architect coder auditor; do
    role_dir="${repo_root}/infra/keys/${role}"
    mkdir -p "${role_dir}"
    cp "${canonical}" "${role_dir}/config"
    chmod 0644 "${role_dir}/config"
done

echo "[render-ssh-config] wrote ${canonical} + 3 role copies"
