#!/bin/bash
# infra/scripts/render-dockerfile.sh
#
# Renders infra/<role>/Dockerfile.generated by composing the static
# template at infra/<role>/Dockerfile with the platform-specific
# install layers from each platform YAML in
# methodology/platforms/<name>.yaml.
#
# Algorithm (matches s009 brief 9.c):
#   1. Read static template, find the '# PLATFORM_INSERT_HERE' sentinel.
#      The template head is everything up to (and not including) the
#      sentinel line; the tail is everything after it.
#   2. Scan all selected platforms for runtime.groups; if any are
#      present, emit a single early USER root + usermod block with the
#      merged group set.
#   3. For each platform, in argument order, emit a per-platform snippet:
#        - apt block (USER root, wrapped install + cache clean)
#        - install block (USER agent, RUN with && chained commands)
#        - env block (one ENV per K=V)
#        - verify block (RUN with && chained commands)
#      Skip blocks the platform doesn't define. Each block ends in
#      USER agent so subsequent template lines have a predictable user.
#   4. Concatenate generated-header + template-head + groups-block +
#      per-platform snippets + template-tail. Write
#      infra/<role>/Dockerfile.generated.
#
# When --platform=default (or no platforms with a relevant role block),
# the only difference between Dockerfile.generated and the static
# template is the generated-header comment and the removal of the
# sentinel line — preserves pre-s009 image behaviour byte-for-byte at
# the build-cache level.
#
# Usage:
#   render-dockerfile.sh <role> <comma-separated-platforms>
#   render-dockerfile.sh --stdout <role> <comma-separated-platforms>
#
# Default mode writes infra/<role>/Dockerfile.generated (and chmods 0444),
# preserving s009's setup-time invocation contract. The --stdout flag
# (added in s013) emits the rendered Dockerfile content to stdout
# instead and is the entry point used by compose-image.sh during JIT
# composition — the caller writes its own tempfile.
#
# Example:
#   render-dockerfile.sh coder-daemon go,python-extras
#   render-dockerfile.sh --stdout auditor platformio-esp32
#
# Exit codes:
#   0  success
#   1  bad arguments / template / YAML
#   2  no PLATFORM_INSERT_HERE sentinel in template

set -euo pipefail

STDOUT_MODE=0
if [ "${1:-}" = "--stdout" ]; then
    STDOUT_MODE=1
    shift
fi

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 [--stdout] <role> <comma-platforms>" >&2
    echo "  role        one of: coder-daemon, auditor, planner, onboarder" >&2
    echo "  platforms   comma-separated platform names; 'default' allowed" >&2
    exit 1
fi

ROLE="$1"
PLATFORMS_CSV="$2"

case "${ROLE}" in
    coder-daemon|auditor|planner|onboarder) ;;
    *) echo "render-dockerfile.sh: unknown role '${ROLE}' (expected coder-daemon, auditor, planner, or onboarder)" >&2; exit 1 ;;
esac

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# shellcheck source=infra/scripts/lib/yaml.sh
. "${repo_root}/infra/scripts/lib/yaml.sh"

template="${repo_root}/infra/${ROLE}/Dockerfile"
output="${repo_root}/infra/${ROLE}/Dockerfile.generated"

if [ ! -f "${template}" ]; then
    echo "render-dockerfile.sh: template not found: ${template}" >&2
    exit 1
fi
if ! grep -q '^# PLATFORM_INSERT_HERE' "${template}"; then
    echo "render-dockerfile.sh: template ${template} has no '# PLATFORM_INSERT_HERE' sentinel" >&2
    exit 2
fi

# Gather per-platform JSON. We pass everything to a single python pass
# so the rendering logic is one cohesive piece (and we pay the yq
# docker-run cost just once per platform).
yaml_pull

# Build a JSON array describing all platforms in order: each entry has
# {name, json}. This avoids re-invoking yq inside the renderer.
platform_jsons=()
IFS=',' read -ra _plats <<< "${PLATFORMS_CSV}"
for raw in "${_plats[@]}"; do
    p="${raw## }"; p="${p%% }"
    [ -z "${p}" ] && continue
    [ "${p}" = "default" ] && continue   # default is a no-op; drop early
    file="${repo_root}/methodology/platforms/${p}.yaml"
    if [ ! -f "${file}" ]; then
        echo "render-dockerfile.sh: platform '${p}' has no YAML at ${file}" >&2
        exit 1
    fi
    platform_jsons+=("$(yaml_to_json "${file}")")
done

# Pass per-platform JSON via a tempfile (one JSON document per line —
# the docs all happen to be single-line because yq emits compact JSON).
# Bash command substitution strips null bytes, so a NUL-delimited env
# var doesn't work; the file route is portable and avoids that footgun.
jsons_file=$(mktemp)
trap 'rm -f "${jsons_file}"' EXIT
for j in "${platform_jsons[@]:-}"; do
    [ -z "${j}" ] && continue
    # yq -o=json '.' emits a multi-line document; collapse to one line
    # via python so we can use newline as the record separator.
    python3 -c 'import json,sys; sys.stdout.write(json.dumps(json.loads(sys.stdin.read())) + "\n")' <<<"${j}" >>"${jsons_file}"
done

# In stdout mode, render to a tempfile then cat to stdout so the
# python heredoc's stdout doesn't fight with bash redirects. In file
# mode, remove any prior generated file (it was chmod 0444 by a
# previous run, which would block the redirect below). The renderer is
# the sole writer for the file-mode path.
if [ "${STDOUT_MODE}" -eq 1 ]; then
    render_target=$(mktemp)
    trap 'rm -f "${jsons_file}" "${render_target}"' EXIT
else
    rm -f "${output}"
    render_target="${output}"
fi

# Hand off to python for the actual rendering.
ROLE="${ROLE}" \
PLATFORMS_CSV="${PLATFORMS_CSV}" \
PLATFORMS_FILE="${jsons_file}" \
TEMPLATE_FILE="${template}" \
python3 - >"${render_target}" <<'PY'
import json, os, sys

role = os.environ["ROLE"]
platforms_csv = os.environ["PLATFORMS_CSV"]
with open(os.environ["TEMPLATE_FILE"]) as f:
    template = f.read()
with open(os.environ["PLATFORMS_FILE"]) as f:
    platforms = [json.loads(line) for line in f if line.strip()]

SENTINEL = "# PLATFORM_INSERT_HERE"

# Split template at the sentinel line. The sentinel line itself is
# discarded; head ends with a newline, tail starts at the line after.
lines = template.splitlines(keepends=True)
head_lines, tail_lines, found = [], [], False
for ln in lines:
    if not found and ln.rstrip("\n").strip() == SENTINEL:
        found = True
        continue
    if not found:
        head_lines.append(ln)
    else:
        tail_lines.append(ln)
if not found:
    print(f"render-dockerfile.sh: sentinel '{SENTINEL}' not found in template", file=sys.stderr)
    sys.exit(2)

head = "".join(head_lines)
tail = "".join(tail_lines)

def render_apt(pkgs):
    quoted = " ".join(pkgs)
    return (
        "RUN apt-get update && apt-get install -y --no-install-recommends \\\n"
        f"        {quoted} \\\n"
        "    && rm -rf /var/lib/apt/lists/*\n"
    )

def render_run(cmds):
    if len(cmds) == 1:
        return f"RUN {cmds[0]}\n"
    body = " \\\n && ".join(cmds)
    return f"RUN {body}\n"

def render_env(env_map):
    # Preserve insertion order (json.loads preserves it on py3.7+).
    out = []
    for k, v in env_map.items():
        sv = str(v)
        if any(c in sv for c in ' \t"\\'):
            esc = sv.replace("\\", "\\\\").replace('"', '\\"')
            out.append(f'ENV {k}="{esc}"')
        else:
            out.append(f"ENV {k}={sv}")
    return "\n".join(out) + "\n"

def render_groups(merged_groups):
    if not merged_groups:
        return ""
    grps = ",".join(merged_groups)
    return (
        "# ---- platform runtime.groups (merged) ----\n"
        "USER root\n"
        f"RUN usermod -a -G {grps} agent\n"
    )

# Aggregate runtime.groups across ALL platforms (not just per-role).
merged_groups = []
seen = set()
for p in platforms:
    rt = p.get("runtime") or {}
    for g in rt.get("groups") or []:
        if g not in seen:
            seen.add(g)
            merged_groups.append(g)

# Build per-platform snippets. Track the active USER as we emit so we
# don't sprinkle redundant USER directives. The groups block (if any)
# leaves us in USER root, so we start each platform from that state;
# otherwise we start fresh (use a sentinel "?" for "unspecified, the
# template's preceding USER root stands").
state = {"user": "root" if merged_groups else "?"}

def ensure_user(chunk, want):
    if state["user"] != want:
        chunk.append(f"USER {want}\n")
        state["user"] = want

snippets = []
for p in platforms:
    role_block = (p.get("roles") or {}).get(role)
    if not role_block:
        continue
    pname = p["name"]
    chunk = [f"# ---- Platform: {pname} ({role}) ----\n"]
    apt = role_block.get("apt") or []
    install = role_block.get("install") or []
    env = role_block.get("env") or {}
    verify = role_block.get("verify") or []
    if apt:
        ensure_user(chunk, "root")
        chunk.append(render_apt(apt))
    if install:
        ensure_user(chunk, "agent")
        chunk.append(render_run(install))
    if env:
        # ENV is user-agnostic; emit without a USER switch so we don't
        # disturb whatever block came before.
        chunk.append(render_env(env))
    if verify:
        # Verify runs as the user who actually exercises the toolchain
        # at runtime (= agent).
        ensure_user(chunk, "agent")
        chunk.append(render_run(verify))
    snippets.append("".join(chunk))

# Renderer contract: the template's tail is written assuming USER state
# is "agent" by the end of the insertion block. If we ended in any other
# state (root after a groups-only block; "?" after no platforms), emit
# USER agent once at the bottom.
trailing_user = ""
if (snippets or merged_groups) and state["user"] != "agent":
    trailing_user = "USER agent\n"
    state["user"] = "agent"

groups_block = render_groups(merged_groups)
mid_parts = []
if groups_block:
    mid_parts.append(groups_block)
mid_parts.extend(snippets)
if trailing_user:
    mid_parts.append(trailing_user)
mid = ("\n" + "\n".join(mid_parts)) if mid_parts else ""

# Generated-file header. Read-protect via permissions later (chmod 0444);
# the comment below is the human-readable equivalent.
header = (
    "# GENERATED by infra/scripts/render-dockerfile.sh — DO NOT EDIT.\n"
    f"# role:      {role}\n"
    f"# platforms: {platforms_csv}\n"
    "# Re-render via: ./setup-linux.sh (or .sh-mac); the renderer runs\n"
    "# in step 5 of setup before 'docker compose build'.\n"
    "\n"
)

sys.stdout.write(header + head + mid + tail)
PY

if [ "${STDOUT_MODE}" -eq 1 ]; then
    # Emit the rendered content to stdout. No chmod, no banner —
    # callers (compose-image.sh) want clean content suitable for
    # `docker build -f -`.
    cat "${render_target}"
else
    # Mark the generated file read-only — a human edit will be silently
    # clobbered on next setup run, and a chmod 0444 makes the contract
    # explicit. The renderer recreates the file each invocation, so the
    # read-only mode never blocks rendering itself.
    chmod 0444 "${output}"
    echo "[render-dockerfile] wrote ${output} (role=${ROLE}, platforms=${PLATFORMS_CSV})"
fi
