#!/bin/bash
# infra/scripts/render-device-override.sh
#
# Renders docker-compose.override.yml at the repo root with a
# 'devices:' block on coder-daemon and auditor when the substrate is
# configured with --device passthrough (s009 9.d). When no devices
# are mapped, removes any prior override file so compose autoload
# falls through to docker-compose.yml unchanged.
#
# Why docker-compose.override.yml at the repo root rather than
# infra/docker-compose.devices.yml: compose autoloads
# docker-compose.override.yml from the project directory, which means
# every existing call site (commission-pair.sh, audit.sh, verify.sh,
# the substrate end-to-end test) transparently picks up the device
# wiring without code changes. The brief flagged the location as
# "pick whichever is cleanest"; this is that. The override file is
# gitignored.
#
# Usage:
#   render-device-override.sh <comma-separated-device-paths>
#
# Empty / no devices → removes any prior override file.
# Non-empty → rewrites the override file to map each path to itself
# inside both coder-daemon and auditor (using the form
# '<host>:<container>' so compose accepts it without ambiguity).

set -euo pipefail

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <comma-separated-host-paths>" >&2
    exit 1
fi

DEVICES_CSV="$1"
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
override="${repo_root}/docker-compose.override.yml"

if [ -z "${DEVICES_CSV}" ]; then
    rm -f "${override}"
    echo "[render-device-override] no devices configured; removed any prior ${override}"
    exit 0
fi

# Build the YAML body. Indented as compose expects.
{
    echo "# GENERATED by infra/scripts/render-device-override.sh — DO NOT EDIT."
    echo "# devices: ${DEVICES_CSV}"
    echo "# Re-render via setup (--device=<path>) or --add-device=<path>."
    echo ""
    echo "services:"
    for role in coder-daemon auditor; do
        echo "  ${role}:"
        echo "    devices:"
        IFS=',' read -ra _devs <<< "${DEVICES_CSV}"
        for d in "${_devs[@]}"; do
            d="${d## }"; d="${d%% }"
            [ -z "${d}" ] && continue
            echo "      - \"${d}:${d}\""
        done
    done
} > "${override}"

echo "[render-device-override] wrote ${override} (devices=${DEVICES_CSV})"
